var timeAct=360; timeIni=360; timeBon=0;
var successes=0; successesMax=5; attempts=0; attemptsMax=3;
var score=0; scoreMax=5; scoreInc=1; scoreDec=1
var typeGame=0;
var tiTime=false;
var tiTimeType=0;
var tiButtonTime=true;
var textButtonTime="Comenzar";
var tiSuccesses=true;
var tiAttempts=true;
var tiScore=true;
var startTime;
var colorBack="#FFFDFD"; colorButton="#91962F"; colorText="#000000"; colorSele="#FF8000";
var goURLNext=false; goURLRepeat=false;tiAval=false;
var scoOk=0; scoWrong=0; scoOkDo=0; scoWrongDo=0; scoMessage=""; scoPtos=10;
var fMenssage="Verdana, Geneva, sans-serif";
var fActi="Verdana, Geneva, sans-serif";
var fEnun="Tahoma, Geneva, sans-serif";
var timeOnMessage=5; messageOk="¡Excelente trabajo! Pasas al siguiente nivel!"; messageTime="¡Tiempo llìmite!  Vuelve a intentarlo"; messageError="¡Upss, Te equivocaste en el orden vuelve a intentarlo-"; messageErrorG="¡Upss, Te equivocaste en el orden vuelve a intentarlo-"; messageAttempts="¡Animo! Repasa y vuelve a intentarlo"; isShowMessage=false;
var urlOk=""; urlTime=""; urlError=""; urlAttempts="";
var goURLOk="_blank"; goURLTime="_blank"; goURLAttempts="_blank"; goURLError="_blank"; 
borderOk="#008000"; borderTime="#FF0000";borderError="#FF0000"; borderAttempts="#FF0000";
var wordsGame="R0kyTjBEZWZh"; wordsStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function giveZindex(typeElement){var valueZindex=0; capas=document.getElementsByTagName(typeElement);
for (i=0;i<capas.length;i++){if (parseInt($(capas[i]).css("z-index"),10)>valueZindex){valueZindex=parseInt($(capas[i]).css("z-index"),10);}}return valueZindex;}
var words=["TGEgR2VzdGnzbiBkZSBsYSBJbmZvcm1hY2nzbiBidXNjYSBmb3J0YWxlY2VyIGVsIHBlcmZpbCBkZSBsb3MgcHJvZmVzaW9uYWxlcyBlbiBlbCDhbWJpdG8gcGVyc29uYWwgeSBsYWJvcmFsLg","TGEgR2VzdGnzbiBkZSBsYSBJbmZvcm1hY2nzbiBvZnJlY2UgaGVycmFtaWVudGFzIHTpY25pY2FzIHkgbel0b2Rvcy4","TGEgR2VzdGnzbiBkZSBsYSBJbmZvcm1hY2nzbiBwZXJtaXRlIGFkcXVpcmlyLCBwcm9kdWNpciB5IHRyYW5zbWl0aXIgZGF0b3MgZSBpbmZvcm1hY2nzbi4","TGEgR2VzdGnzbiBkZSBsYSBJbmZvcm1hY2nzbiBkZWJlIGV4aGliaXIgY2FsaWRhZCwgZXhhY3RpdHVkIHkgYWN0dWFsaWRhZC4","TGEgR2VzdGnzbiBkZSBsYSBJbmZvcm1hY2nzbiBzZSBvcmllbnRhIGEgbG9ncmFyIG9iamV0aXZvcyBwcm9wdWVzdG9zIGRlIGxhIG9yZ2FuaXphY2nzbi4"];imaW=["","","","",""];queW=["","","","",""]; c=[109,68,89,74,89];
var auW=["","","","",""];
var actMaxWidth="1000"; actMaxHeight="400";indexG=0;profG=0;dirMedia="GI2N0Defa_resources/media/"; textBNext="";
var wordsG=[];imageW=[];questionW=[];audioW=[];cG=[];
colorText="#000000";colorButton="#0099FF";colorBack="#FFFFFF";colorSele="#DEEDFE";tiAval=true;
fMenssage="Verdana, Geneva, sans-serif";fActi="Verdana, Geneva, sans-serif";fEnun="Verdana, Geneva, sans-serif";
